# Generated by Django 3.0 on 2019-12-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Enter the latitude at which squirrel was sighted', max_length=100)),
                ('longitude', models.FloatField(help_text='Enter the longitude at which squirrel was sighted', max_length=100)),
                ('uniqid', models.CharField(help_text='Enter the unique squirrel id', max_length=50, unique=True)),
                ('shift', models.DateField(help_text='Birth Date')),
                ('date', models.DateField(help_text='Enter the date of sighting')),
                ('age', models.CharField(help_text='Enter the age: only adult,juvenile or leave blank', max_length=50)),
                ('primaryfurcolor', models.CharField(help_text='Enter the fur color of squirrel', max_length=50)),
                ('location', models.CharField(help_text='Enter location of squirrel', max_length=50)),
                ('specificlocation', models.CharField(help_text='Enter the specific location of squirrel', max_length=50)),
                ('pecificlocation', models.CharField(help_text='Enter the specific location of squirrel', max_length=100)),
                ('running', models.BooleanField(help_text='Was the squirrel running?')),
                ('chasing', models.BooleanField(help_text='Was the squirrel chasing?')),
                ('climbing', models.BooleanField(help_text='Was the squirrel climbing?')),
                ('eating', models.BooleanField(help_text='Was the squirrel running?')),
                ('otheractivities', models.CharField(help_text='Enter the activity of squirrel', max_length=100)),
                ('kuks', models.BooleanField(help_text='Does squirrel kuks?')),
                ('quaas', models.BooleanField(help_text='Does squirrel quaa?')),
                ('moans', models.BooleanField(help_text='Does squirrel moan?')),
                ('tailflags', models.BooleanField(help_text='Did squirrel have tailflags?')),
                ('tailtwiches', models.BooleanField(help_text='Did squirrel have tailtwiches?')),
                ('approaches', models.BooleanField(help_text='Did squirrel approach?')),
                ('indifferent', models.BooleanField(help_text='Did squirrel was indifferent?')),
                ('runsfrom', models.BooleanField(help_text='Did squirrel run from?')),
            ],
        ),
    ]
