# Generated by Django 3.0 on 2019-12-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sightings',
            fields=[
                ('X', models.FloatField(help_text='Latitude')),
                ('Y', models.FloatField(help_text='Longitude')),
                ('Unique_Squirrel_ID', models.CharField(default=None, help_text='Enter the unique squirrel id', max_length=50, primary_key=True, serialize=False)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='shift of sighting', max_length=2)),
                ('Date', models.DateField(blank=True, help_text='Date')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=50, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Enter the fur color of squirrel', max_length=50, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Enter location of squirrel', max_length=50, null=True)),
                ('Specific_Location', models.CharField(blank=True, help_text='Enter the specific location of squirrel', max_length=250, null=True)),
                ('Running', models.BooleanField(default=True, help_text='Is it running?')),
                ('Chasing', models.BooleanField(default=True, help_text='Is it chasing?')),
                ('Climbing', models.BooleanField(default=True, help_text='Is it climbing?')),
                ('Eating', models.BooleanField(default=True, help_text='Is it eating?')),
                ('Foraging', models.BooleanField(default=True, help_text='Is it foraging?')),
                ('Other_Activities', models.CharField(blank=True, help_text='Enter the activity of squirrel', max_length=100, null=True)),
                ('Kuks', models.BooleanField(default=True, help_text='Is it kuking?')),
                ('Quaas', models.BooleanField(default=True, help_text='Is it quaaing?')),
                ('Moans', models.BooleanField(default=True, help_text='Is it moaning?')),
                ('Tail_flags', models.BooleanField(default=True, help_text='Is it having tailflags?')),
                ('Tail_twitches', models.BooleanField(default=True, help_text='Is it having tail twitches?')),
                ('Approaches', models.BooleanField(default=True, help_text='Is it approaching?')),
                ('Indifferent', models.BooleanField(default=True, help_text='Is it indifferent?')),
                ('Runs_from', models.BooleanField(default=True, help_text='Is it running from the sighter?')),
            ],
        ),
        migrations.DeleteModel(
            name='squirrels',
        ),
    ]
