# Generated by Django 3.0 on 2019-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191209_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, default='9999-12-31', help_text='ate', null=True),
        ),
    ]
