# Generated by Django 3.0 on 2019-12-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191209_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, default='12-31-9999', help_text='ate', null=True),
        ),
    ]
