# Generated by Django 3.0 on 2019-12-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20191209_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Enter location of squirrel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Enter the fur color of squirrel', max_length=50, null=True),
        ),
    ]
